#!/bin/bash

for DIR in ./*/; do
(
    TEST=$(echo $DIR | cut -c3- | rev | cut -c2- | rev)

    if [ -f "$TEST/build.sh" ]; then

        echo Test $TEST

        cd $DIR

        ./build.sh
        ./run.sh

        cd ..

    fi
) &
done

wait
