#!/bin/bash

wmake libso libraries/briscolaCore
wmake libso libraries/briscolaMesh
wmake libso libraries/briscolaFiniteVolume
wmake libso libraries/briscolaVolumeOfFluid
wmake libso libraries/briscolaTwoPhase

wmake applications/utilities/briscolaCheckMesh

wmake applications/solvers/briscolaLaplacian
wmake applications/solvers/briscolaColocated
wmake applications/solvers/briscolaStaggered
wmake applications/solvers/briscolaVofAdvection
