#!/bin/bash

PACKAGE=superlu_dist
VERSION=9.1.0

# This is the installation location, can be modified:
PREFIX=$HOME/opt/$PACKAGE-$VERSION

# Build type (Release or Debug)
BUILD_TYPE=Release

case $1 in

    -clean)

        rm -fr build/$PACKAGE
        rm -fr $PREFIX

        echo "$PACKAGE removed"

        ;;

    -*|--*)

        echo "Unknown option $1"
        exit 1

        ;;

    *)

        if [ ! -d "build/$PACKAGE" ]; then

            if [ ! -f "$PACKAGE-$VERSION.tar.gz" ]; then

                echo "No file $PACKAGE-$VERSION.tar.gz found"
                exit

            fi

            mkdir -p build

            tar xzf $PACKAGE-$VERSION.tar.gz -C build || \
                { echo "Extraction of $PACKAGE failed"; exit; }

            mv build/$PACKAGE-$VERSION build/$PACKAGE

        fi

        mkdir -p build/$PACKAGE/build
        cd build/$PACKAGE/build

        cmake \
            -DTPL_ENABLE_PARMETISLIB=OFF \
            -DTPL_ENABLE_CUDALIB=OFF \
            -DTPL_ENABLE_HIPLIB=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_STATIC_LIBS=OFF \
            -DXSDK_ENABLE_Fortran=OFF \
            -Denable_examples=OFF\
            -Denable_tests=OFF \
            -Denable_python=OFF \
            -DCMAKE_INSTALL_PREFIX=$PREFIX \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            .. || \
                { echo "CMake command for $PACKAGE failed"; exit; }

        make -j ${WM_NCOMPPROCS:-4} || \
            { echo "Compilation of $PACKAGE failed"; exit; }

        make install || { echo "Installation of $PACKAGE failed"; exit; }

        echo "$PACKAGE built"

        echo ""
        echo "Add"
        echo ""
        echo "export SUPERLU_DIST_HOME=$PREFIX"
        echo "export LD_LIBRARY_PATH=\$SUPERLU_DIST_HOME/lib:\$LD_LIBRARY_PATH"
        echo ""
        echo "to your shell's rc file"

        ;;
esac
