#!/bin/bash

PACKAGE=eigen
VERSION=3.4.0

# This is the installation location, can be modified:
PREFIX=$HOME/opt/$PACKAGE-$VERSION

case $1 in

    -clean)

        rm -fr build/$PACKAGE
        rm -fr $PREFIX

        echo "$PACKAGE removed"

        ;;

    -*|--*)

        echo "Unknown option $1"
        exit 1

        ;;

    *)

        if [ ! -d "build/$PACKAGE" ]; then

            if [ ! -f "$PACKAGE-$VERSION.tar.gz" ]; then

                echo "No file $PACKAGE-$VERSION.tar.gz found"
                exit

            fi

            mkdir -p build

            tar xzf $PACKAGE-$VERSION.tar.gz -C build || \
                { echo "Extraction of $PACKAGE failed"; exit; }

            mv build/$PACKAGE-$VERSION build/$PACKAGE

        fi

        mkdir -p build/$PACKAGE/build
        cd build/$PACKAGE/build

        cmake \
            -DCMAKE_INSTALL_PREFIX=$PREFIX \
            .. || { echo "CMake command for $PACKAGE failed"; exit; }

        make install || { echo "Installation of $PACKAGE failed"; exit; }

        echo "$PACKAGE built"

        echo ""
        echo "Add"
        echo ""
        echo "export EIGEN_HOME=$PREFIX"
        echo ""
        echo "to your shell's rc file"

        ;;
esac
