#!/bin/bash

PACKAGE=superlu_dist
VERSION=9.1.0

case $1 in

    -clean)

        rm -fr build/$PACKAGE
        rm -fr platform/${WM_OPTIONS}/$PACKAGE

        echo "$PACKAGE removed"

        ;;

    -*|--*)

        echo "Unknown option $1"
        exit 1

        ;;

    *)

        if [ "$WM_PROJECT" != "OpenFOAM" ]; then

            echo "OpenFOAM is not loaded"
            exit

        fi

        if [ ! -d "build/$PACKAGE" ]; then

            if [ ! -f "$PACKAGE-$VERSION.tar.gz" ]; then

                echo "No file $PACKAGE-$VERSION.tar.gz found"
                exit

            fi

            mkdir -p build

            tar xzf $PACKAGE-$VERSION.tar.gz -C build || \
                { echo "Extraction of $PACKAGE failed"; exit; }

            mv build/$PACKAGE-$VERSION build/$PACKAGE

        fi

        DEPENDENCIES=$(pwd)

        mkdir -p build/$PACKAGE/build
        cd build/$PACKAGE/build

        PREFIX=$DEPENDENCIES/platforms/$WM_OPTIONS/$PACKAGE

        cmake \
            -DTPL_ENABLE_INTERNAL_BLASLIB=ON \
            -DTPL_ENABLE_PARMETISLIB=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -Denable_examples=OFF\
            -Denable_tests=OFF \
            -Denable_python=OFF \
            -DCMAKE_INSTALL_PREFIX=$PREFIX \
            .. || \
                { echo "CMake command for $PACKAGE failed"; exit; }

        make -j $WM_NCOMPPROCS || \
            { echo "Compilation of $PACKAGE failed"; exit; }

        make install || { echo "Installation of $PACKAGE failed"; exit; }

        cd $DEPENDENCIES

        echo "$PACKAGE built"

        ;;
esac
