namespace Foam
{

CS_UNARY_FUNCTION(vertexScalar, vertexScalar, sqrt)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, cbrt)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, sign)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, pos)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, pos0)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, neg)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, neg0)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, exp)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, log)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, sin)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, cos)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, tan)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, asin)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, acos)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, atan)
CS_UNARY_FUNCTION(vertexScalar, vertexScalar, erf)

}
