namespace Foam
{

CS_UNARY_FUNCTION(edgeScalar, edgeScalar, sqrt)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, cbrt)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, sign)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, pos)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, pos0)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, neg)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, neg0)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, exp)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, log)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, sin)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, cos)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, tan)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, asin)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, acos)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, atan)
CS_UNARY_FUNCTION(edgeScalar, edgeScalar, erf)

}
